# NFT Verification Portal 設定例
# このファイルを参考に、実際の値でwrangler.tomlを設定してください

[env.production.vars]
# Discord Bot設定
DISCORD_TOKEN = "your_discord_bot_token_here"
DISCORD_GUILD_ID = "your_discord_guild_id_here"
DISCORD_ROLE_ID = "your_discord_role_id_here"

# Suiネットワーク設定
SUI_NETWORK = "mainnet"  # mainnet, testnet, devnet

# NFTコレクション設定
# 実際のNFTコレクションIDを設定してください
NFT_COLLECTION_ID = "0x1234567890abcdef::my_nft::MyNFT"

# 例: カスタムNFTコレクション
# NFT_COLLECTION_ID = "0x2::nft::NFT"

# 例: 特定のNFTタイプ
# NFT_COLLECTION_ID = "0x1234567890abcdef::game::GameNFT"

# 例: 空の場合はすべてのNFTタイプを検索
# NFT_COLLECTION_ID = ""

# API設定
API_BASE_URL = "https://your-api-domain.workers.dev"
VERIFICATION_URL = "https://your-verification-domain.workers.dev"
ADMIN_USER_ID = "your_admin_user_id_here"

# KVストレージ設定
[[env.production.kv_namespaces]]
binding = "BES_ROLES"
id = "your_kv_namespace_id_here"

# 開発環境設定
[env.development.vars]
DISCORD_TOKEN = "DEV_TOKEN"
DISCORD_GUILD_ID = "DEV_GUILD_ID"
DISCORD_ROLE_ID = "DEV_ROLE_ID"
SUI_NETWORK = "testnet"
NFT_COLLECTION_ID = "DEV_COLLECTION_ID"
API_BASE_URL = "http://localhost:8787"
VERIFICATION_URL = "http://localhost:8787"
ADMIN_USER_ID = "DEV_ADMIN_USER_ID"

[[env.development.kv_namespaces]]
binding = "BES_ROLES"
id = "your_dev_kv_namespace_id_here" 